name: Wiki Sync

on:
  push:
    branches:
      - main
    paths:
      - "wiki/**"
  gollum:

env:
  GIT_AUTHOR_NAME: pgxkit-bot
  GIT_AUTHOR_EMAIL: actions@github.com

jobs:
  sync-docs-to-wiki:
    name: Sync Documentation to Wiki
    runs-on: ubuntu-latest
    if: github.event_name != 'gollum'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Update timestamp in Home.md
        run: |
          # Update the timestamp in the Home file before syncing
          TIMESTAMP=$(date -u '+%B %Y')
          sed -i "s/\*Last updated: December 2024\*/\*Last updated: $TIMESTAMP\*/" wiki/Home.md
      
      - name: Sync wiki to GitHub Wiki
        uses: newrelic/wiki-sync-action@main
        with:
          source: wiki
          destination: wiki
          token: ${{ secrets.GITHUB_TOKEN }}
          gitAuthorName: ${{ env.GIT_AUTHOR_NAME }}
          gitAuthorEmail: ${{ env.GIT_AUTHOR_EMAIL }}

  sync-wiki-to-docs:
    name: Sync Wiki to Documentation
    runs-on: ubuntu-latest
    if: github.event_name == 'gollum'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: main
      
      - name: Sync GitHub Wiki to wiki directory
        uses: newrelic/wiki-sync-action@main
        with:
          source: wiki
          destination: wiki
          token: ${{ secrets.GITHUB_TOKEN }}
          gitAuthorName: ${{ env.GIT_AUTHOR_NAME }}
          gitAuthorEmail: ${{ env.GIT_AUTHOR_EMAIL }}
          branch: main
      
      - name: Reset timestamp placeholder in Home.md
        run: |
          # Reset timestamp to placeholder after syncing from wiki
          if [ -f wiki/Home.md ]; then
            sed -i 's/\*Last updated: [A-Za-z]* [0-9]*\*/\*Last updated: December 2024\*/' wiki/Home.md
          fi
      
      - name: Commit timestamp reset
        run: |
          if git diff --quiet; then
            echo "No changes to commit"
          else
            git config --local user.email "${{ env.GIT_AUTHOR_EMAIL }}"
            git config --local user.name "${{ env.GIT_AUTHOR_NAME }}"
            git add wiki/Home.md
            git commit -m "chore(docs): Reset timestamp placeholder after wiki sync [skip-ci]"
            git push
          fi 